### ISSUE TITLE
Request: Cover or contain

### ISSUE THREAD

**Issue by Heilemann** [cswendrowski/FoundryVTT-Streaming-Mode#1]
I wish there was a way to control for each scene just what the zoom level would be. The default scene in our game is a title card with a huge graphic and the title written on it, and I want that to cover the viewport. That's true for a couple of other scenes, but most often I really want it to contain the scene, maybe with a bit of room around it.

Some scenes show up quite small; it seems like maybe they aren't zoomed beyond 1:1? Feels like they should.

Also it feels like the centering should take into account whether the sidebar is open.

Thanks!

**Comment by cswendrowski** [comment]
These are good suggestions!

Scale in Foundry is from 0 (most zoomed out) to 3 (most zoomed in). It's possible to have a map that's so large that even 0 zoom doesn't show the entire map.

Currently Streaming mode scales from 0-1 based on map ratio: `1 - (canvas.dimensions.sceneHeight / canvas.dimensions.height) }` This works well for some maps, but not for others, and other options I've tried just shift the problem around.

I will add a per-scene setting to manually set the scene's zoom, defaulting to the calculated one if not present.

I'll see if I can get the sidebar size when centering

**Comment by Heilemann** [comment]
I think I run into the 1.xx range on some of my scenes.

The problem with setting it manually is that everyone's on different sized computers. I'm on a huge screen, my players might be on laptops, so any fixed zoom level is going to be weird for one of us.

**Comment by cswendrowski** [comment]
@Heilemann try out v1.0.2 when you get a chance, I reworked the scaling logic!
